// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfqtupwtzceatqvlednl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcXR1cHd0emNlYXRxdmxlZG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTAzMzUsImV4cCI6MjA3MTUyNjMzNX0.SxBD1qRs2SXaEzMPKLNc6fZYkACavZd5SuwV740Ur5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});